### PR TITLE
Don't fail miserably - but show a console.error

### PR DESCRIPTION
**Pull request by wiredearp**
@nealstewart: Perhaps this can make us survive the occasional crash on Docs startup (see https://github.com/Tradeshift/Client-Runtime/issues/141) until we can take a week off to dig into the problem.

### CODE REVIEW

**Comment by nealstewart** [comment]
You've added a number of guards, but it's not clear to me what the situations that cause these are. Can you add a comment describing WHY the sibings and other elements are not present?

Should they fail when they're not present? Is it a bug in Spiritual, a misconfiguration, or what? Failing silently seems fishy.

**Comment by nealstewart** [comment]
Also tests. You were talking about how you didn't have enough in this repo ;)

**Comment by wunderbyte** [comment]
I don't know why the siblings and elements are not present. It's a race condition that only manifests online and when the file is not in the browser cache, so it's hard to debug. Adding a test wouldn't help (under these conditions). Anyways, we don't fail silently, since there's a console.error presented; we just don't fail miserably any more.

**Comment by wunderbyte** [comment]
Tests are in the pipeline. Some way down the pipeline.

**Comment by wiredearp** [comment]
The fix seems to have cured the problem with Docs freezing on startup, so I think it's been sucessfully tested. Next step is to get rid of the many weird `if`s.

**Pull request merged**
